### ISSUE TITLE
typo in helm-chart-sonarqube/charts/sonarqube-lts/values.yaml

### ISSUE THREAD

**Issue by silvio201** [SonarSource/helm-chart-sonarqube#103]
There is a typo in your values file in the initFs section:

it says enabeld but i think it means enabled

![Screenshot from 2021-10-08 13-27-19](https://user-images.githubusercontent.com/46531457/136548969-740aad42-ccd8-4383-b9fd-4e4030adb2ac.png)

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @silvio201 ,

thanks for reporting this. It is already known as reported in #24 and fixed for the latest chart with #27 . sadly this fix does not qualify for being backported to the LTS helm chart as this is not a blocker :/
