### ISSUE TITLE
Support for 1.18?

### ISSUE THREAD

**Issue by skashmeri** [SonarSource/helm-chart-sonarqube#108]
Hey, just wondering if theres an older branch or tag with 1.18 support or if you are going to support older versions? not everyone is using the latest greatest version of k8s.

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @skashmeri ,

basically i can second what @k3rnelpan1c-dev wrote. there is no plan to support EOL versions of k8s for this helm chart. The support for 1.19 will probably dropped after a grace period as well
