### ISSUE TITLE
403 error after deploying 

### ISSUE THREAD

**Issue by usuryadevara** [SonarSource/helm-chart-sonarqube#111]
deployed helm chart with this configuration but i am seeing 403 error. 

ebsstorageclass
`kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: postgres-sc
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Retain
mountOptions:
  - debug
volumeBindingMode: Immediate`

persistence volume postgres:
`apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    fsType: xfs
    volumeID: aws://us-east-1a/vol-064228df12f591d2a
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem`

sonarqube-persistent:
`apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonar-pv
spec:
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    fsType: xfs
    volumeID: aws://us-east-1a/vol-0e23fe2c2518f19b9
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  # hostPath:
  #   path: "/mnt/data"
  #storageClassName: gp2-retain
  storageClassName: ""
  volumeMode: Filesystem`

`nginx:
  enabled: true

ingress:
  enabled: false
  # Used to create an Ingress record.
  hosts:
    - name: sonarqube-sandbox.test.com
      # Different clouds or configurations might need /* as the default path
      path: /
      # For additional control over serviceName and servicePort
      # serviceName: someService
      # servicePort: somePort
  annotations: {}
  kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  # This property allows for reports up to a certain size to be uploaded to SonarQube
  nginx.ingress.kubernetes.io/proxy-body-size: "8m"`

` #kubectl get pods -n sonarqube
NAME                                                  READY   STATUS    RESTARTS   AGE
sonarqube-ingress-nginx-controller-6fc6459b95-7s828   1/1     Running   0          5h6m
sonarqube-postgresql-0                                1/1     Running   0          5h6m
sonarqube-sonarqube-0                                 1/1     Running   0          5h6m
# kubectl get svc -n sonarqube
NAME                                           TYPE           CLUSTER-IP       EXTERNAL-IP                                                              PORT(S)                      AGE
sonarqube-ingress-nginx-controller             LoadBalancer   172.20.245.113   a684c4bea36eb4cf28f292a059da7ddd-19189938.us-east-1.elb.amazonaws.com   80:32159/TCP,443:31136/TCP   5h6m
sonarqube-ingress-nginx-controller-admission   ClusterIP      172.20.224.250   <none>                                                                   443/TCP                      5h6m
sonarqube-postgresql                           ClusterIP      172.20.80.157    <none>                                                                   5432/TCP                     5h6m
sonarqube-postgresql-headless                  ClusterIP      None             <none>                                                                   5432/TCP                     5h6m
sonarqube-sonarqube                            ClusterIP      172.20.74.62     <none>                                                                   9000/TCP                     5h6m`

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @usuryadevara ,

the format of your issue makes it really hard to understand what you did and where you are facing a [403](https://http.cat/403) error. could you make it a little more clear?

**Comment by usuryadevara** [comment]
The issue is with PV and PVC, if i create them manually its working fine for ebs volume. Any suggestions on the steps. I think its volume issue.
`apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    fsType: xfs
    volumeID: aws://us-east-1a/vol-064228df12f591d2a
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  # hostPath:
  #   path: "/mnt/data"
  #storageClassName: gp2-retain
  storageClassName: ""
  volumeMode: Filesystem`

`apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonar-pv
spec:
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    fsType: xfs
    volumeID: aws://us-east-1a/vol-0e23fe2c2518f19b9
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem`

**Comment by tobias-trabelsi-sonarsource** [comment]
if the application is starting up just fine i highly doubt that the PV/PVC creation is related. it is still not clear to me where you get a 403. if it is when you try to access the web ui i would rather focus on the ingress creation.

please explain EXACTLY the issue that you are facing and format your `values` using markdown

**Comment by usuryadevara** [comment]
Thanks for the reply. I created 2 PV manually and that fixed the problem, 

i still don't know which one caused the problem, may be the order of using these volumes.
`postgres-pv           20Gi       RWO            Retain           Bound         sonarqube/sonarqube-sonarqube                                   11d
sonar-pv              20Gi       RWO            Retain           Bound         sonarqube/data-sonarqube-postgresql-0                           11d`

**Comment by tobias-trabelsi-sonarsource** [comment]
with these information me neither :shrug: i still have no idea where you were facing a 403 but if the problem magically resolved itself i would go ahead and close this issue as it does not seem to be related to the helm chart
