### ISSUE TITLE
CrashLoopBack & OOMKills

### ISSUE THREAD

**Issue by arthurlogilab** [SonarSource/helm-chart-sonarqube#115]
Trying to deploy sonarqube via this helm chart it's failing to deploy with Crash LoopBack and sometimes OOMKill as the pod status. 

```
sonarqube 11:20:13.99 
sonarqube 11:20:14.00 Welcome to the Bitnami sonarqube container
sonarqube 11:20:14.00 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-sonarqube
sonarqube 11:20:14.00 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-sonarqube/issues
sonarqube 11:20:14.00 
sonarqube 11:20:14.01 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
sonarqube 11:20:14.06 INFO  ==> Creating SonarQube configuration
sonarqube 11:20:14.13 INFO  ==> Trying to connect to the database server
sonarqube 11:20:14.17 INFO  ==> Restoring persisted SonarQube installation
sonarqube 11:20:14.21 INFO  ==> Setting heap size to -Xmx2048m -Xms1024m
sonarqube 11:20:14.24 INFO  ==> ** SonarQube setup finished! **

sonarqube 11:20:14.26 INFO  ==> ** Starting SonarQube **
Running SonarQube...
wrapper  | --> Wrapper Started as Console
wrapper  | Launching a JVM...
jvm 1    | Wrapper (Version 3.2.3) http://wrapper.tanukisoftware.org
jvm 1    |   Copyright 1999-2006 Tanuki Software, Inc.  All Rights Reserved.
jvm 1    | 
jvm 1    | 2021.11.05 11:20:15 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /opt/bitnami/sonarqube/temp
jvm 1    | 2021.11.05 11:20:15 INFO  app[][o.s.a.es.EsSettings] Elasticsearch listening on [HTTP: 127.0.0.1:9001, TCP: 127.0.0.1:35993]
jvm 1    | 2021.11.05 11:20:15 INFO  app[][o.s.a.ProcessLauncherImpl] Launch process[[key='es', ipcIndex=1, logFilenamePrefix=es]] from [/opt/bitnami/sonarqube/elasticsearch]: /opt/bitnami/sonarqube/elasticsearch/bin/elasticsearch
jvm 1    | 2021.11.05 11:20:15 INFO  app[][o.s.a.SchedulerImpl] Waiting for Elasticsearch to be up and running
jvm 1    | 2021.11.05 11:20:16 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [es]: 137
jvm 1    | 2021.11.05 11:20:16 INFO  app[][o.s.a.SchedulerImpl] Process[es] is stopped
jvm 1    | 2021.11.05 11:20:16 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
wrapper  | <-- Wrapper Stopped
```

I would expect the `request.memory` to warn if the 2Go are not available for the deployment to work. 

The 2 nodes have an allocatable capacity of 2.8Go. 

Am I missing something ? could the `sysctl` sidecar be failing silently ?

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @arthurlogilab ,

i am rather certain that this is not the output from one of our official images as [they start the `sonar-application.jar` directly](https://github.com/SonarSource/docker-sonarqube/blob/master/9/community/sonar.sh) and do not use the wrapper like [the bitnami images](https://github.com/bitnami/bitnami-docker-sonarqube/blob/master/9/debian-10/rootfs/opt/bitnami/scripts/sonarqube/run.sh). the beginning of the sonarqube output reminds me of the bitnami framework in general. 

> sonarqube 11:20:14.26 INFO  ==> ** Starting SonarQube **

are you using [their chart](https://github.com/bitnami/charts/tree/master/bitnami/sonarqube) maybe?
if you can provide more logs (specially `web.log` and `es.log`) i might be able to help you why the application is not starting but the bitnami chart is not in our control and you should ask for support there

**Comment by arthurlogilab** [comment]
hi @tobias-trabelsi-sonarsource 

thanks a lot for getting back so quickly, you're perfectly right, I'm on the wrong project, sorry for the noise and I'll go report this to the correct project.
