### ISSUE TITLE
Unable to set password in Sonarqube helm file

### ISSUE THREAD

**Issue by TheRayTracer** [SonarSource/helm-chart-sonarqube#120]
Hi,

Within a cloud environment (AWS) deployment using a policy controller such as Rancher that enforces cpu and memory limits, it is not possible to use the chart setting: account.adminPassword

When the chart setting: account.adminPassword is used, a small pod is created that does not allow it's cpu nor memory limits to be set.

The work-around is not to use the account.adminPassword chart setting, and manually change the admin password upon first deployment.

Would it be possible to add settings to allow the cpu and memory limits to be set for this small password change pod?

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @TheRayTracer ,

thank you for raising this point and explaining the issue you are facing with it. I created https://jira.sonarsource.com/browse/DOCKER-37 to track the progress on adding the needed limits for the hook in question :slightly_smiling_face:

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @TheRayTracer ,

fixed with in #141. release is still pending but the implementation is done
