### ISSUE TITLE
No imagePullSecrets in change-admin-password-hook.yaml

### ISSUE THREAD

**Issue by mrombout** [SonarSource/helm-chart-sonarqube#127]
No `imagePullSecrets` is configured for `change-admin-password-hook.yaml` through `image.pullSecret` like it is for other images being pulled (e.g. in `sonarqube-lts.yaml`). This makes it impossible for me at the moment to use the `account.adminPassword` since I do not have access to the public Docker Hub registry where I am deploying.

I can pick this up along with #126, if that's okay!

**Comment by tobias-trabelsi-sonarsource** [comment]
Fixed with #126 :+1:
