### ISSUE TITLE
Ability to switch edition without redefining image tag

### ISSUE THREAD

**Issue by z0rc** [SonarSource/helm-chart-sonarqube#129]
AFAIU to switch for Community to Developer edition, I need to set `image.tag` value to `9.2.1-developer`. But here is the problem, image tag defines version too. So in future chart updates I need to track changes to this default value and update my values accordingly. This is unwelcome side effect of switching editions, I don't what to track image tag version changes in addition to helm chart version.

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @z0rc ,

this is indeed a correct understanding from your side. and if i understand your problem with this correctly, you don't want to maintain two versions on your own (chart version and manual overwrite the image tag whenever a new version is released)? This is a fair point and i created [DOCKER-39 ](https://jira.sonarsource.com/browse/DOCKER-39) to track this.

**Comment by EugenMayer** [comment]
I'am really not sure why any lengthy argument needs to be made about this, sorry. Paying customers like most probably @z0rc and us are basically the fooled ones here.

We have to ensure to pick the right image version manually every time we upgrade the helm chart. Manually. Just as paying customers do expect it.

At the same time, community editions, which are free, can role just the easy way.

There is no way I can justify this decision or even the concept of this in a helm chart of a commercial product.

Sorry for the fairly harsh comment, but how in the world does this need commenting at all.
