### ISSUE TITLE
sonarSecretProperties only used if sonarProperties also specified

### ISSUE THREAD

**Issue by krische** [SonarSource/helm-chart-sonarqube#135]
## Description
I noticed something when installing SonarQube with the helm chart. If you only specify `sonarSecretProperties` when deploying and don't specify any `sonarProperties`; then none of the `sonarSecretProperties` get used. I didn't try it in the other direction (only specifying `sonarProperties`), but I would imagine that behaves the same way. I say this because I noticed that both the [Deployment](https://github.com/SonarSource/helm-chart-sonarqube/blob/master/charts/sonarqube/templates/deployment.yaml#L141) and [StatefulSet](https://github.com/SonarSource/helm-chart-sonarqube/blob/master/charts/sonarqube/templates/sonarqube-sts.yaml#L111) seem to run those properties through an `and` conditional.

## Workaround
I was able to work around my issue but just specifying at least one property in `sonarProperties`; that way both had some values specified and thus all of the properties were imported.

## Expected Behavior
I would expect that only one of those parameters needs specifying, not both.

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @krische ,

thanks for the report. I completely agree that this is unexpected behavior and can be improved. I created [DOCKER-49](https://jira.sonarsource.com/browse/DOCKER-49) to track this
