### ISSUE TITLE
Typo in Readme.md 

### ISSUE THREAD

**Issue by fredbzh56** [SonarSource/helm-chart-sonarqube#147]
In https://github.com/SonarSource/helm-chart-sonarqube/blob/master/charts/sonarqube-lts/README.md
there is a typo : 
readinessProbe.initialDelaySecond
livenessProbe.initialDelaySecond
startupProbe.initialDelaySecond

insteadof : (second with an S)

readinessProbe.initialDelaySeconds
livenessProbe.initialDelaySeconds
startupProbe.initialDelaySeconds

**Comment by tobias-trabelsi-sonarsource** [comment]
Thanks for the report again :+1: 
i have created [DOCKER-48](https://jira.sonarsource.com/browse/DOCKER-48) to track this
