### ISSUE TITLE
value: livenessProbe.failureThreshold never used

### ISSUE THREAD

**Issue by fredbzh56** [SonarSource/helm-chart-sonarqube#148]
In https://github.com/SonarSource/helm-chart-sonarqube/blob/master/charts/sonarqube-lts/templates/sonarqube-sts.yaml
The  key : LivenessProbe.failureThreshold  is never set.

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @fredbzh56 ,

thanks for the report. it seems to be missing from all templates :eyes: 
I created [DOCKER-47](https://jira.sonarsource.com/browse/DOCKER-47) to track this
