### ISSUE TITLE
[Q] outdated alpine-wget image

### ISSUE THREAD

**Issue by k3rnelpan1c-dev** [SonarSource/helm-chart-sonarqube#15]
I have noticed that you are using the `rjkernick/alpine-wget` image, which is quite outdated and does not seem to be maintained anymore.
Due to this I spun up a [very slim repo myself](https://github.com/k3rnelpan1c-dev/alpine-wget) with as much automation as possible to keep it up to date, that is based on a current version of Alpine that I am using for our install of this chart. (due to security limitations placed upon the images we can deploy)

If you want to use a up to date image feel free to use mine or copy the behaviour found in #10 and switch to the curl images entirely. (note: you could have also kept the wget there as long as you would have used the `rjkernick/alpine-wget`, which thanks to the full install of wget respects the proxy settings)

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @k3rnelpan1c-dev ,

yeah you have a good point there. i think in terms of maintenance it makes sense to copy the behavior of #10 to go with the official curl images. do you want to create a PR for this as well? i highly appreciate your effort here :slightly_smiling_face: 
if you don't want to create one i will take care about this when i am back from vacation (after next week)

**Comment by k3rnelpan1c-dev** [comment]
Definitely can do!
