### ISSUE TITLE
Inconsistency in plugins installation

### ISSUE THREAD

**Issue by gbonnefille** [SonarSource/helm-chart-sonarqube#156]
The strategies to install plugins differ between the chart sonarqube and sonarqube-lts.

What is the reason for that?
Can we merge both codes?

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @gbonnefille ,

the sonarqube-lts is only meant to be working with the current LTS of SonarQube and therefor follows the same patch policy as the LTS (only fix blocker bugs). all improvements have been done on the sonarqube chart which is only meant to be working with the latest release of sonarqube.

so to answer your second question: no we can not merge both codes.

hope that makes sense
