### ISSUE TITLE
Need tag for latest release

### ISSUE THREAD

**Issue by dwi-mfbcs** [SonarSource/helm-chart-sonarqube#168]
I don't seem to see a tag available for the latest release (non dce version). Can we have a tag created for this?

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @dwi-mfbcs ,

it [this](https://github.com/SonarSource/helm-chart-sonarqube/tree/sonarqube-2.0.0-sonarqube-dce-1.0.0) the tag you are looking for?

**Comment by dwi-mfbcs** [comment]
It must be it. I guess I was "tricked" by the `dce` mentioned in the tag name.
Thanks.
