### ISSUE TITLE
Release latest charts

### ISSUE THREAD

**Issue by kevin-utilus** [SonarSource/helm-chart-sonarqube#175]
Hi,

I recently fixed a bug in the charts but that doesn't seem to be available in the chart repo yet. Would it be possible to get the latest versions in the git repo available in the chart repo?

Thanks!

**Comment by gaiazov** [comment]
+1 would love to see the latest chart released 🚀 👍

**Comment by galgross** [comment]
Hi, any update on latest chart?

**Comment by tobias-trabelsi-sonarsource** [comment]
Hello Folks :wave: 

i have talked with the SQ PM about this and he does currently not see the need to release the helm charts yet. you can expect a release at latest with the next SQ Release (scheduled for end of March / beginning of April).
In the mean time, you are free to use the current reference branch to benefit from the fixes that are already present in this repository.

i know that this is a very disappointing answer, but this is the only one that i can give you right now.

**Comment by leo-geoffroy-sonarsource** [comment]
@kpink224 Standard and DCE versions were released last week, alongside with SonarQube 9.4
