### ISSUE TITLE
Update to Postgresql chart v11.x

### ISSUE THREAD

**Issue by mtcolman** [SonarSource/helm-chart-sonarqube#177]
Hello, not so much an issue, more of a query. With the release of [Bitnami PostgreSQL chart v11.x](https://github.com/bitnami/charts/tree/master/bitnami/postgresql) (which uses PostgreSQL app version 14.x), do you have plans to update the requirement in the SonarQube chart to utilise it?

(Current PostgreSQL on the [SonarQube chart](https://github.com/SonarSource/helm-chart-sonarqube/tree/master/charts/sonarqube) is `version: 10.15.0` and `appVersion: 11.14.0`).

Thanks!

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @mtcolman ,

thanks for the ping. i have seen that there are some bigger changes in the bitnami postgresql chart so i created [DOCKER-59](https://jira.sonarsource.com/browse/DOCKER-59)  to track this
