### ISSUE TITLE
Side containers in latest LTS chart

### ISSUE THREAD

**Issue by dcoraboeuf** [SonarSource/helm-chart-sonarqube#185]
**Describe the bug**

The `extraContainers` configuration has been introduced into the `sonarqube` chart, but not in the `sonarqube-lts` chart.

**Versions used:**

- Chart Version: 1.0.25+248

Would it be possible to port the `extraContainers` feature to the LTS chart?

Thank,
Damien

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @dcoraboeuf ,

sadly i don't think this will be ported to the LTS chart :disappointed: If you want to use sidecar containers, please switch to the latest release and the sonarqube chart.
