### ISSUE TITLE
Allow setting license(s) via chart values

### ISSUE THREAD

**Issue by pathob** [SonarSource/helm-chart-sonarqube#189]
Dear SonarSource team,

it would be nice to be able to set license(s) via chart values for non-CE instances of SonarQube. Other product's charts like from [Artifactory](https://github.com/jfrog/charts/blob/5d31b82c3b3efaca449b38a9a253814a386042d9/stable/artifactory/values.yaml#L478) or the [Atlassian Data Center charts](https://github.com/atlassian/data-center-helm-charts/blob/73fb4f2c20426ada26c0a292c3ae94e20423ff5a/src/main/charts/jira/values.yaml#L464) are good examples for that. Being able to do this allows engineers to inject all kind of secrets into the application from a Vault or similar just during the Helm deployment.

I'm looking forward for your feedback

Thank you and many regards
Patrick

**Comment by leo-geoffroy-sonarsource** [comment]
Hi @pathod,

Thanks for the report, this feature is indeed not supported by the helm chart as of now.
Since it is a new feature request, could you please open a new thread in the forum https://community.sonarsource.com/c/suggestions/features?

**Comment by pathob** [comment]
Hi @leo-geoffroy-sonarsource,

before closing this issue, it would be interesting to know, whether SonarQube supports another way besides the UI to set licenses (I couldn't find any). If there is another a way, preferentially via the filesystem, I could contribute a pull request to introduce this feature.

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @pathob ,

there is none for the filesystem. There is an API endpoint (POST `api/editions/set_license`) but using it would result in similar downside as the change admin password hook, therefor we will probably not implement this without a change of the application in the helm chart. As there is currently no feature request for this, you should go ahead and create this feature request as stated by my colleague @leo-geoffroy-sonarsource
