### ISSUE TITLE
Improve change-admin-password mechanism

### ISSUE THREAD

**Issue by pathob** [SonarSource/helm-chart-sonarqube#190]
Dear SonarSource team,

the SonarQube charts offer a very basic mechanism for changing the admin password. However, due to the imperative approach it is incompatible with the declarative character of Kubernetes. For most of the cases it is not even possible to provide the old and the new password. In most cases, the old password is technically 'gone' when the new password should be set.

Another problem with this feature is that it's not consistent among all charts. E.g. the DCE chart allows setting `imagePullSecrets` while the LTS chart does not. And also, the current mechanism does not work when using a custom application context (set via properties).

SonarQube's [security documentation](https://docs.sonarqube.org/latest/instance-administration/security/) describes how to reset a forgotten password and Bitnami has a [AWS SonarQube administration documentation](https://docs.bitnami.com/aws/apps/sonarqube/administration/change-admin-password/) that already describes on how to automate this mechanism even more.

Based on all this, I would suggest the following mechanism. A new job uses the psql CLI to:

1. Try to rename the default admin user to that username (to be discussed)
2. if 1. is not possible and if no user for the defined username exists, create a user with the defined username (to be discussed)
3. Grant administration rights for the user with the defined username if rights still missing (optional)
4. Set the new salted and hashed password for the user with the defined username

The related YAML could look like this:

```
admin:
  username: "admin"
  password:
  secret:
  dataKey:
```

For a higher compatibility, this would also be acceptable:

```
account:
  username: "admin"
  password:
  secret:
  dataKey:
```

For this issue, I could even try to do the contribution myself, but I would like to hear your feedback first.

Thank you and many regards
Patrick

**Comment by leo-geoffroy-sonarsource** [comment]
Hi @pathod,

Thank you for your request.
The database of SonarQube should be treated as a blackbox, we only want to interact with it through its standard API.
Using psql cli would therefore defeat that purpose, and would also increase the complexity as we would also need to support multiple DBMS here and not just Postgresql.
Since API needs authentication, we indeed need the old admin password and I agree with you that the solution is not ideal. We hope that there will be an effort in the future to support more configuration as code for SonarQube but as long as this is not the case we stick with the current mechanism as a way to help and not a enforced solution for everyone.

**Comment by pathob** [comment]
Hi @leo-geoffroy-sonarsource

I find it a little disconcerting how quickly my tickets are closed. For example, I explained that the current mechanism is not consistent among all charts and this broken:

> Another problem with this feature is that it's not consistent among all charts. E.g. the DCE chart allows setting imagePullSecrets while the LTS chart does not. And also, the current mechanism does not work when using a custom application context (set via properties).

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @pathob ,

the LTS chart follows (sadly) the same patch policy as the application and this does not fulfill the criteria of a blocker bug. you can still log in via the the web ui and change the password there. there is no enforcement to use the post install hook.
Improvements were already done for the latest chart and if you want to benefit from them i recommend you to use the latest chart with the latest version of SQ
