### ISSUE TITLE
Unify SonarQube charts

### ISSUE THREAD

**Issue by pathob** [SonarSource/helm-chart-sonarqube#191]
Dear SonarSource team,

separate Helm charts for separate product versions like here for SonarQube CDE or SonarQube LTS is something that we can see in other vendor's charts too, e.g. [Artifactory](https://github.com/jfrog/charts/tree/master/stable). Having different charts for basically the same product, however, is hard for both, chart developers and users and leads to gaps between charts, e.g. the admin password job as mentioned in #190.

For this reason I would like to encourage you to find solutions together with the application development team to unify those charts into a single chart (just like Artifactory did recently) that allows scaling up a CE instance to a DCE instance just by increasing the number of replicas and adding license(s) (see #189), but not by using another chart.

I'm looking forward for your feedback.

Thank you and many regards
Patrick

**Comment by leo-geoffroy-sonarsource** [comment]
Hi @pathod,

The split of helm charts between CE/DE/EE edition and DCE edition is intended, as switching from one to the other requires important architectural decisions to be made for the setup.
DCE edition is not just an increase of replicas of the standard editions, but brings a lot of clustering capabilities that needs to be setup.
We want to keep that distinction, so there are no plan to unify them in a single chart in the long term.
