### ISSUE TITLE
Update Chart.yaml apiVersion to v2

### ISSUE THREAD

**Issue by davewin93** [SonarSource/helm-chart-sonarqube#194]
**Describe the bug**
Since helm3 is the only supported version the chart should use apiVersion: v2 to reflect that. This is documented here https://helm.sh/docs/topics/charts/#the-apiversion-field

**Versions used:**
- Chart Version: 2.0.7
- SonarQube Version: 9.3.0
- Helm Version: helm3
- Kubernetes Version: v1.21

**Expected behavior**
apiVersion should be v2

**Comment by leo-geoffroy-sonarsource** [comment]
Hi @davewin93  ,

Thank you for raising this point. I have created the ticket https://jira.sonarsource.com/browse/DOCKER-64 to track the progress

**Comment by davewin93** [comment]
Thanks for the followup @leo-geoffroy-sonarsource :)

**Comment by leo-geoffroy-sonarsource** [comment]
I close the issue, progress can be followed on the ticket itself
