### ISSUE TITLE
postgresql.enabled = false fails with error

### ISSUE THREAD

**Issue by kmilner** [SonarSource/helm-chart-sonarqube#20]
Disabling postgresql causes the following error (e.g. when running `helm template sonarqube ./helm-chart-sonarqube/charts/sonarqube --output-dir . --set postgresql.enabled=false`):

```Error: YAML parse error on sonarqube/templates/secret.yaml: error converting YAML to JSON: yaml: line 11: did not find expected key```

Removing the second hyphen to prevent chomping right on the following line fixes this, although to be honest I'm not entirely sure why chomping right whitespace causes a problem in this case.
 https://github.com/SonarSource/helm-chart-sonarqube/blob/32ffdaae67aec0d2b89a75a003920e1308711132/charts/sonarqube/templates/secret.yaml#L14

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @kmilner ,

thanks for the report. the right chomping removes every white space ignoring new line characters, resulting in a invalid yaml file as the `---` that should indicate a new file are pushed to the data previously :see_no_evil: 
i will take care about that soon
