### ISSUE TITLE
Question about replicaCount

### ISSUE THREAD

**Issue by blazej-budzynski** [SonarSource/helm-chart-sonarqube#201]
Hi,

There were recently two issues opened (#186 and #193) where it was said that replicaCount has to be always set to 1. However, the explanations of "why" were rather short. I checked the setup with SQ deployed as StatefulSet with three pods running and an external database and everything was running just ok, with no problems whatsoever. So, before rolling this up to production (other teams within my company), I would like to know the risk, like what exactly can go wrong and under which circumstances (e.g. what does it mean "database corruption").

Thanks,

**Comment by leo-geoffroy-sonarsource** [comment]
Hi @blazej-budzynski 

Here is already a discussion on the topic : https://community.sonarsource.com/t/sonarqube-in-aks-with-more-than-one-replica/51892

If you still need more information about it, I invite you to comment on the community forum as this topic is more related to SQ itself than the helm chart
