### ISSUE TITLE
Unable to save configurations in Sonarqube after setting context path

### ISSUE THREAD

**Issue by sooraj2589** [SonarSource/helm-chart-sonarqube#205]
**Describe the bug**
we have deployed sonarqube in helm and recenlty configured the context path to /sonarqube using env sonar.web.context. Aslo modified the probe settings as below

**Versions used:**
- SonarQube Version: 9.3

readinessProbe:
  initialDelaySeconds: 120
  periodSeconds: 30
  failureThreshold: 6
  sonarWebContext: /sonarqube/

livenessProbe:
  initialDelaySeconds: 120
  periodSeconds: 30
  failureThreshold: 6
  sonarWebContext: /sonarqube/

startupProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 24
  sonarWebContext: /sonarqube
```

This is working fine when we removed context path and set it to "/". Can any one please advise?

**Comment by leo-geoffroy-sonarsource** [comment]
Hi @sooraj2589 
To configure the context path of SonarQube, you should use the env variable SONAR_WEB_CONTEXT as decribed below: https://docs.sonarqube.org/latest/setup/environment-variables/
```yaml
ApplicationNodes:
    env:
    - name: SONAR_WEB_CONTEXT
      value: /sonarqube
```

You also forgot a trailing slash on sonarWebContext of startupProbe

**Comment by leo-geoffroy-sonarsource** [comment]
Hi @sooraj2589 ,

We are running internally an instance with the same context as yours, so I confirm the following configuration should work as expected:
`ApplicationNodes:
    env:
    - name: SONAR_WEB_CONTEXT
      value: /sonarqube`

We also have an additional configuration for the ingress:
`ingress:
  enabled: true
  # Used to create an Ingress record.
  hosts:
    - name: <url_of_sonarqube>
      # Different clouds or configurations might need /* as the default path
      path: /sonarqube/
      # For additional control over serviceName and servicePort
      # serviceName: someService
      # servicePort: somePort`

Why does the pod is not running?

**Comment by Lerentis** [comment]
@leo-geoffroy-sonarsource 

> ```yaml
> ApplicationNodes:
>     env:
>     - name: SONAR_WEB_CONTEXT
>       value: /sonarqube`
> ```

the scope `ApplicationNodes` only available in the DCE chart...
