### ISSUE TITLE
Unable to define multiple ingress backends to a single host

### ISSUE THREAD

**Issue by tmetodie** [SonarSource/helm-chart-sonarqube#207]
**Describe the bug**
It would be great if we use the Helm chart to define multiple backends to the same host in Ingress object.

**Versions used:**
- Chart Version: latest at this point in time
- SonarQube Version: 9.4.0
- Helm Version:
- Kubernetes Version: 1.21

**Expected behavior**
Able to define multiple 
**Screenshots**

**Additional context**
It is needed when we want to use AWS ALB ingress controller and perform redirect from HTTP to HTTPS.

<snip>
spec:
  rules:
  - host: $APPLICATION_URL
    http:
      paths:
      - backend:
          service:
            name: ssl-redirect
            port:
              name: use-annotation
        path: /*
        pathType: ImplementationSpecific
      - backend:
          service:
            name: %env.application_name%-sonarqube-lts
            port:
              name: http
        path: /*
        pathType: ImplementationSpecific
<snip>

**Comment by leo-geoffroy-sonarsource** [comment]
Hi @tmetodie 
Thank you for the feedback, as it is a[ feature request](https://github.com/SonarSource/helm-chart-sonarqube#contributing), could you please create a new thread in the [forum?](https://community.sonarsource.com/c/suggestions/features)
Please try to add as much information as you can.
Thanks
