### ISSUE TITLE
[docs] What are valid values for .Values.edition

### ISSUE THREAD

**Issue by flickerfly** [SonarSource/helm-chart-sonarqube#213]
**Describe the bug**
Chart documentation doesn't specify specific values for the edition key. 

**Expected behavior**
When reading the README at https://github.com/SonarSource/helm-chart-sonarqube/blob/master/charts/sonarqube/README.md, I expect to find a list of valid values for keys like "edition".

Alternately, I'd expect the values.yaml to provide a comment that specifies what values are appropriate.

**Comment by leo-geoffroy-sonarsource** [comment]
Hello @flickerfly 

That makes sense I have open a [PR](https://github.com/SonarSource/helm-chart-sonarqube/pull/217) for that
