### ISSUE TITLE
init-fs unable to chown configmap 

### ISSUE THREAD

**Issue by chas0amx** [SonarSource/helm-chart-sonarqube#25]
In my case, next code mounts read-only config into init-fs container and **chown** failed
```
            {{- else if or .Values.sonarProperties (not .Values.elasticsearch.bootstrapChecks) }}
            - mountPath: {{ .Values.sonarqubeFolder }}/conf/
              name: config
            {{- end }}
```
https://github.com/SonarSource/helm-chart-sonarqube/blob/master/charts/sonarqube/templates/sonarqube-sts.yaml#L146

```
 kubectl logs sonarqube-sonarqube-0 -c init-fs
chown: /opt/sonarqube/conf/..2021_05_26_13_12_03.339819096/sonar.properties: Read-only file system
chown: /opt/sonarqube/conf/..2021_05_26_13_12_03.339819096: Read-only file system
chown: /opt/sonarqube/conf/..2021_05_26_13_12_03.339819096: Resource temporarily unavailable
chown: /opt/sonarqube/conf/sonar.properties: Read-only file system
chown: /opt/sonarqube/conf/..data: Read-only file system
chown: /opt/sonarqube/conf: Read-only file system
chown: /opt/sonarqube/conf: Read-only file system

```

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @chas0amx ,

can you describe your use case why you want to configure SQ via `sonar.properties` and not via environment variables? 

i have been thinking about dropping this possibility here as it is only there because of the last LTS (7.9) and you should be able to configure SQ using environment variables to the full extend as well.

**Comment by chas0amx** [comment]
Thank you for your advice. I am going to move into ENV.

**Comment by chas0amx** [comment]
@tobias-trabelsi-sonarsource Is it possible to configure email settings via env variables? 
Found a similar question https://github.com/SonarSource/docker-sonarqube/pull/417/commits/fe5dc7e3611635d351bbcdeae42951e93e288a7b but there is no solution.

**Comment by tobias-trabelsi-sonarsource** [comment]
nope. feel free to watch [SONAR-11818](https://jira.sonarsource.com/browse/SONAR-11818) as a possible solution will hopefully come with this resolved.
