### ISSUE TITLE
Chart does not work on its own due to hard-coded postgres url

### ISSUE THREAD

**Issue by evanrich** [SonarSource/helm-chart-sonarqube#3]
in the sonarqube-sts.yaml template, there is a busybox job that tries to connect to your postgresql server using a hardcoded value:

```
command: ["/bin/sh", "-c", "for i in $(seq 1 200); do nc -z -w3 {{ .Release.Name}}-postgresql 5432 && exit 0 || sleep 2; done; exit 1"]
```
this causes the pod to never start.  I had to change this to

```
command: ["/bin/sh", "-c", "for i in $(seq 1 200); do nc -z -w3 {{ .Values.postgresql.postgresqlServer}} 5432 && exit 0 || sleep 2; done; exit 1"]
```

to make it work.   hardcoding the "-postgresql" in the name is a bad idea.  I'm assuming this is due to the optional bundled postgresql server option, but I'm using an external server.

**Comment by tobias-trabelsi-sonarsource** [comment]
good catch! this init container should not run when you are not using the bundled postgresql. i created a PR to fix this
