### ISSUE TITLE
too long container name

### ISSUE THREAD

**Issue by Hokwang** [SonarSource/helm-chart-sonarqube#30]
Hi,

You need to fix container name about password-hook.

```
$ helm install -n sonarqube-stage sonarqube-stage-sonarqube -f sonarqube-stage-sonarqube-values.yaml ../helm-chart-sonarqube/charts/sonarqube/
Error: failed post-install: warning: Hook post-install sonarqube/templates/change-admin-password-hook.yml failed: Job.batch "sonarqube-stage-sonarqube-sonarqube-change-admin-password-hook" is invalid: spec.template.spec.containers[0].name: Invalid value: "sonarqube-stage-sonarqube-sonarqube-change-default-admin-password": must be no more than 63 characters
```

**Comment by k3rnelpan1c-dev** [comment]
well this one is interesting, yet not too surprising given that the chart literally appends the full name everywhere and may apply the 63 char limit on the full name but not on the full appended name of anything :frowning_face: 

FYI the chart will auto append `-sonarqube` to the Sonarqube pod so you could drop it from your deployment name, however that is more a bandage than a fix.

**Comment by k3rnelpan1c-dev** [comment]
The longest `name` appendix in the whole chart is **30** chars long (actually within the `change-admin-password-hook.yml` file that prompted your error here).

A possible 'solution' would be to limit full names globally to 33 chars therefor never exceeding 63 chars the other solution is to apply a trim on a per `name` property.
Either you artificially limit the 'full name', but have the same prefix on every k8s object of the helm install or you have a more dynamic prefix length based on the length of the appendix, but risk inconsistent prefixes for the k8s objects of the helm install.

**Comment by Hokwang** [comment]
Hi,

thanks for your comments.

I usally use below form.

```
k create ns sonarqube-stage
```
I use `-stage` and `-prod` ns.

```
helm install -n sonarqube-stage sonarqube-stage-postgresql bitnami/postgresql
helm install -n sonarqube-stage sonarqube-stage-sonarqube <helm chart path>
```
I prefer to install DB myself. 
so the name is `<namespace>-<tool>` because several tools can be in here one namespace.

anyway, for now, I use `fullnameOverride: sonarqube-stage-sonarqube` for workaround.

**Comment by tobias-trabelsi-sonarsource** [comment]
Following up here on a discussion that @k3rnelpan1c-dev and i had in #32 

@Hokwang can you elaborate your use case where you need to have such long release names in rather long namespaces? 

while @k3rnelpan1c-dev has proven that we could reduce the risk of a user facing the issue that you described i see this rather as something that a kubernetes administrator should know and can work their way around without needing to change the template. it makes sense that we mention this in our documentation for sure but still this seems like an edge case to me. 
That said, i am happy to be proven otherwise

**Comment by Hokwang** [comment]
@tobias-trabelsi-sonarsource 
ok then I will close this case.

btw, I think the method of changing the admin password should be fundamentally re-implemented by tool it self, not kubernetes hook.
