### ISSUE TITLE
ingress.yaml has error

### ISSUE THREAD

**Issue by Hokwang** [SonarSource/helm-chart-sonarqube#34]
Hi,

I am using k8s 1.17 version.
now ingress.yaml does not work for me.

if you can change flie like below,
it works well!

```
{{- if .Values.ingress.enabled -}}
{{- $serviceName := include "sonarqube.fullname" . -}}
{{- $servicePort := .Values.service.externalPort -}}
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" -}}
apiVersion: networking.k8s.io/v1
{{- else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress" -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ template "sonarqube.fullname" . }}
  labels:
    app: {{ template "sonarqube.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.ingress.labels }}
{{ .Values.ingress.labels | toYaml | trimSuffix "\n"| indent 4 -}}
{{- end}}
{{- if .Values.ingress.annotations}}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
{{- end }}
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
spec:
...
```

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @Hokwang ,

kubernetes 1.17 is eol since January if i recall correctly. you should probably take this as a hint to update your cluster :wink:

**Comment by Hokwang** [comment]
@tobias-trabelsi-sonarsource 
that's right, but when if you edit, you can support whole version of kuberentes simply.

**Comment by tobias-trabelsi-sonarsource** [comment]
tbh i don't think it makes sense to create a compatibility for a kubernetes version that was eol before we even published this helm chart. also we are very explicit which version of k8s and sq are currently supported in the [README.md](https://github.com/SonarSource/helm-chart-sonarqube/blob/master/charts/sonarqube/README.md)
