### ISSUE TITLE
Create "route" for OpenShift deployments

### ISSUE THREAD

**Issue by gasgithub** [SonarSource/helm-chart-sonarqube#48]
Would be nice to have option to create Route instead of Ingress fro OpenShift deployments :-)

Here is updated PR with this https://github.com/SonarSource/helm-chart-sonarqube/pull/49

**Comment by os-learner** [comment]
Nice to see sonarqube helm chart support for OpenShift deployments.
What is the ETA of this issue to be merged to master?

**Comment by tobias-trabelsi-sonarsource** [comment]
as @gasgithub seems unresponsive since last week i will probably close his PR and do the necessary changes later today when i find the time :shrug:

**Comment by os-learner** [comment]
@tobias-trabelsi-sonarsource ,
Thanks for making necessary changes and committing. Can I use the branch to deploy sonarqube on my non-prod cluster?

**Comment by tobias-trabelsi-sonarsource** [comment]
@os-learner feel free. i am waiting for a review from another sonarsourcer to merge this to master. if you detect anything before that i'd be happy to get to hear about it :+1:
