### ISSUE TITLE
When using sonarproperties and sonarsecret properties with statefullset it fails with:Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

### ISSUE THREAD

**Issue by daximillian** [SonarSource/helm-chart-sonarqube#50]
When using sonarproperties and sonarsecret properties together with a statefulset the pod fails with the following message:

`Error: failed to start container "sonarqube": Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/kubelet/pods/8683f3ba-661b-4b30-b14f-18fbd26e0fcd/volume-subpaths/concat-dir/sonarqube/0\\\" to rootfs \\\"/var/lib/docker/overlay2/13bae27b3b57f85e28f44b88a993093a2e9d1e79596d6790bdd581f4ae3357ba/merged\\\" at \\\"/var/lib/docker/overlay2/13bae27b3b57f85e28f44b88a993093a2e9d1e79596d6790bdd581f4ae3357ba/merged/opt/sonarqube/conf/sonar.properties\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type`

This issue doesn't occur when using a deployment. 
Please fix the mountpoints for the sts.

**Comment by k3rnelpan1c-dev** [comment]
Hmmm, this is innteresting.
My guess as to what is going wrong here is this malformed (incorrect indent in line 23-25):
https://github.com/SonarSource/helm-chart-sonarqube/blob/0e367bb9bd3312802b463b8b91fe1dadd73c6774/charts/sonarqube/templates/config.yaml#L15-L25

If you could test by changing the indent of this template in your checked out copy and try to apply your config again?

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sonarqube.fullname" . }}-config
  labels:
    app: {{ template "sonarqube.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- if and .Values.sonarSecretKey (not .Values.sonarProperties) (not .Values.elasticsearch.bootstrapChecks) }}
  sonar.properties: sonar.secretKeyPath={{ .Values.sonarqubeFolder }}/secret/sonar-secret.txt
  {{- end }}
  {{- if or .Values.sonarProperties (not .Values.elasticsearch.bootstrapChecks) }}
  sonar.properties:
  {{ range $key, $val := .Values.sonarProperties }}
    {{ $key }}={{ $val }}
  {{ end }}
  {{- if not .Values.elasticsearch.bootstrapChecks }}
    sonar.es.bootstrap.checks.disable=true
  {{- end }}
  {{- end }}
  {{- if and .Values.sonarSecretKey .Values.sonarProperties }}
    sonar.secretKeyPath={{ .Values.sonarqubeFolder }}/secret/sonar-secret.txt
  {{- end }}
```

**Comment by daximillian** [comment]
The problem is not with the indentation but with the volumes and the volume mounts.
Compare the definitions for properties, secret.properties and concat-dir between the deployment template and the sts template. 

deployment.yaml:
```
          volumeMounts:
            - mountPath: /tmp/props/sonar.properties
              name: config
              subPath: sonar.properties
            - mountPath: /tmp/props/secret.properties
              name: secret-config
              subPath: secret.properties
            - mountPath: /tmp/result
              name: concat-dir
			  
```
sonarqube-sts.yaml:
```
  volumeMounts:
  {{- if .Values.persistence.mounts }}
  {{ toYaml .Values.persistence.mounts | indent 12 }}
  {{- end }}
              {{- if and .Values.sonarProperties .Values.sonarSecretProperties }}
              - mountPath: {{ .Values.sonarqubeFolder }}/conf/sonar.properties
                subPath: sonar.properties
                name: concat-dir
              {{- else if or .Values.sonarProperties (not .Values.elasticsearch.bootstrapChecks) }}
              - mountPath: {{ .Values.sonarqubeFolder }}/conf/sonar.properties
                subPath: sonar.properties
                name: config
              {{- end }}
```

**Comment by k3rnelpan1c-dev** [comment]
you right, my bad for totally misinterpreting that log :sweat_smile:

**Comment by tobias-trabelsi-sonarsource** [comment]
looking at the implementation this could never had worked. the concat init container is missing from the sts as well. i'll fix this asap :see_no_evil:
