### ISSUE TITLE
Cannot connect to the DB after restarting the pod

### ISSUE THREAD

**Issue by sabotensaboten** [SonarSource/helm-chart-sonarqube#52]
I can't connect to the DB after restarting the pod.

As a prerequisite, we do not use the default PostgreSQL, but install and use PostgreSQL on an external virtual server that we have prepared.
The PostgreSQL version is 13.1.

I can connect the first time without any problem, but when I restart the pod, I get the following error.

```2021.07.13 09:41:36 ERROR Web[][o.s.s.p.PlatformImpl] Web server startup failed: Database colums [geometry_columns.f_table_catalog] must have UTF8 charset.```

Is there a solution to this problem?

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @sabotensaboten ,

this error is not related to the helm chart i fear. as you can see from our [requirements documentation](https://docs.sonarqube.org/latest/requirements/requirements/#header-3) the database must be configured to use UTF-8 charset. SQ detects that this is not the case for `Database colums [geometry_columns.f_table_catalog]` in your case and ist refusing to start. 
if you need help with this, i think your best bet is to create a thread in our [community forum](https://community.sonarsource.com/) about that
