### ISSUE TITLE
Issue with dependencies

### ISSUE THREAD

**Issue by bordenit** [SonarSource/helm-chart-sonarqube#54]
helm dependency update is failing with Sonarqube chart (which makes the helm chart fail):

```
[name@host helm-chart-sonarqube]$ helm dependency update --debug
Error: Chart.yaml file is missing
helm.go:88: [debug] Chart.yaml file is missing
helm.sh/helm/v3/pkg/chart/loader.LoadFiles
        helm.sh/helm/v3/pkg/chart/loader/load.go:158
helm.sh/helm/v3/pkg/chart/loader.LoadDir
        helm.sh/helm/v3/pkg/chart/loader/directory.go:119
helm.sh/helm/v3/pkg/downloader.(*Manager).loadChartDir
        helm.sh/helm/v3/pkg/downloader/manager.go:228
helm.sh/helm/v3/pkg/downloader.(*Manager).Update
        helm.sh/helm/v3/pkg/downloader/manager.go:154
main.newDependencyUpdateCmd.func1
        helm.sh/helm/v3/cmd/helm/dependency_update.go:74
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.1.3/command.go:852
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.1.3/command.go:960
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.1.3/command.go:897
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:87
runtime.main
        runtime/proc.go:225
runtime.goexit
        runtime/asm_amd64.s:1371
```
A recommendation is to package the dependencies and this repo into release with helm package and include in repo releases.

Then change the instructions on the this page here to use the packages that already exist rather than encouraging users to build off master branch:
https://docs.sonarqube.org/latest/setup/sonarqube-on-kubernetes/

**Comment by k3rnelpan1c-dev** [comment]
While I agree that a packaged version of this chart is desirable and is in the works based on the comments by tobias in #11, however, your Helm output should have already told you whats wrong.
It cannot find the `Chart.yaml` cause you seem to brunning the helm command from the root of this repo, when the Chart and its templates are within the subfolder `charts/sonarqube`. 
If you run the `helm dependency update` within that folder it should work without any problem.

**Comment by jesseborden** [comment]
I’ll try that later today, but I thought I tried both and the instructions seem off if that is true:

Per the instructions on the page linked above you have helm dependency update in the helm-chart-Sonarqube folder:
…
git clone https://github.com/SonarSource/helm-chart-sonarqube.git
cd helm-chart-sonarqube
helm dependency update
kubectl create namespace sonarqube
helm upgrade --install -f values.yaml -n sonarqube sonarqube ./
…

**Comment by bordenit** [comment]
I’ll try that later today, but I thought I tried both and the instructions seem off if that is true:

Per the instructions on the page linked above you have helm dependency update in the helm-chart-Sonarqube folder:
…
git clone https://github.com/SonarSource/helm-chart-sonarqube.git
cd helm-chart-sonarqube
helm dependency update
kubectl create namespace sonarqube
helm upgrade --install -f values.yaml -n sonarqube sonarqube ./
…

**Comment by bordenit** [comment]
Thanks it worked. You should change the instructions on https://docs.sonarqube.org/latest/setup/sonarqube-on-kubernetes to the correct cd command.

**Comment by k3rnelpan1c-dev** [comment]
Hi bordenit,

Glad it worked :tada:!
I may be a contributor, however I am in no way associated with SonarSource, so all I can do is ping @tobias-trabelsi-sonarsource.

@ tobias: Sorry to ping you but there indeed seems to be an error within the SonarQube Docs in regards to how precisely this chart needs to be 'built'. Out of curiosity, what would be the appropriate way to report such an error?

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @k3rnelpan1c-dev and thank you very much for handling this issue :heart: 

usually we try to consolidate all input in the [community forum](https://community.sonarsource.com/) to have more in depth discussions and also to reach more people.  
i have created a documentation ticket to track this in our jira [SONAR-15199](https://jira.sonarsource.com/browse/SONAR-15199)
