### ISSUE TITLE
Permanent Server id

### ISSUE THREAD

**Issue by simonoff** [SonarSource/helm-chart-sonarqube#6]
Hello,

there is a question how to make the sever id permanent?

**Comment by mikeycmccarthy** [comment]
I'm not an expert on this one but I'm almost entirely positive that the server id is based on the jdbc connection string. SonarSource recommend you contact them if the JDBC connection string is going to change as they'll need to generate you a new license.

Keep your JDBC connection string the same and I believe you'll be good.

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @simonoff ,

the answer from @mikeycmccarthy is correct. the server id does not change as long as the jdbc url does not change, so you should be good to go. in general when you have questions like this, feel free to ask them in the community forum as there are more people that could help you :)

**Comment by simonoff** [comment]
Ok, then I think we need to ask to set the password for postgres if its running from chart. And make that the postgres host name all the time the same and notice its in NOTE.txt .Or in docs.
