### ISSUE TITLE
[Q] Plugin installation directory

### ISSUE THREAD

**Issue by keke8273** [SonarSource/helm-chart-sonarqube#66]
Hi All, thank you for putting this helm chart together.

When I use the chart to install sonarqube plugins, the plugin `jar` files are first downloaded to `/opt/sonarqube/extensions/downloads` directory.  I was expecting `/opt/sonarqube/extensions/plugins` directory. But no big deal. 

Then somewhere after the `web` process is started and before the `ce` process is started, the plugin `jar` files  are **moved** from `/opt/sonarqube/extensions/downloads` to `/opt/sonarqube/extensions/plugins`. 

Is this the intended behaviour of the chart?

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @keke8273 ,

yeah this is intended behavior by sonarqube. the helm chart is only giving a way to download the plugins before the application starts. the moving of the jars is done by SQ itself.

hope that answers your question. if you have additional questions, feel free to create a topic in our [community forum](https://community.sonarsource.com/) :)
