### ISSUE TITLE
Support for additional (sidecar) containers

### ISSUE THREAD

**Issue by dlbock** [SonarSource/helm-chart-sonarqube#73]
The current helm chart configuration has support for `extraInitContainers` but not for additional (sidecar) containers to run alongside the `sonarqube` container. (I may be wrong, I searched but failed to find, so would love for someone to correct me!)

One example of where this would be helpful:
We run SonarQube via this helm chart on GKE, using a PostgreSQL instance on Cloud SQL. In order for the `sonarqube` container to be able to establish a connection to that Cloud SQL instance, Google [recommends to use the Cloud SQL Auth proxy](https://cloud.google.com/sql/docs/postgres/connect-kubernetes-engine). The way to do that is to run the `cloud-sql-proxy` as a sidecar, an additional container sharing a pod with the `sonarqube` container.

As we manage our infrastructure using Terraform, and this helm chart isn't hosted anywhere at the moment, we've cloned this GitHub repository, copied over the contents of `charts/sonarqube/*` and made modifications directly in `charts/sonarqube/templates/sonarqube-sts.yaml` to add the additional `cloud-sql-proxy` container.

Once this chart is hosted somewhere, and we want to switch to pulling it directly from that hosted location, having a configuration value to specify additional containers would be helpful/necessary in order to achieve the aforementioned example above. Otherwise we'd still have to keep a copy of the entire chart in order to make the needed modifications.

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @dlbock ,

you are correct. there is currently no support for sidecar containers as documented [here](https://docs.sonarqube.org/latest/setup/sonarqube-on-kubernetes/#header-3). there is currently nothing in the pipe to change that, but we are aware of this limitation and will hopefully work on improving the situation soon. if somebody in the mean time would introduce sidecar support via a PR, that would help :slightly_smiling_face: 

regarding the missing helm repository; this will hopefully change soon :tm:

**Comment by dlbock** [comment]
> if somebody in the mean time would introduce sidecar support via a PR, that would help

@tobias-trabelsi-sonarsource Of course! I somehow forgot that that was possible 😓. Here you go: #74

**Comment by tobias-trabelsi-sonarsource** [comment]
closed with #74 
thanks again :slightly_smiling_face:
