### ISSUE TITLE
Use with Istio Ingress Gateway - GKE

### ISSUE THREAD

**Issue by xylene314** [SonarSource/helm-chart-sonarqube#80]
Hi Team,
Am planning to use Istio-Ingresss gateway. Do we need to enable ?

```
ingress:
  enabled: true
```

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @xylene314 ,

setting `ingress.enabled` to `true` will create a ingress record. we did not test every ingress provider but the spec should work if you set the right annotation. of cause you are always free to set this to `false` and create the ingress record yourself.

for general support questions, feel free to create a thread in our [community forum](https://community.sonarsource.com/) so more people can have a look :)
