### ISSUE TITLE
Using the helm chart with AzureSQL

### ISSUE THREAD

**Issue by JimFran** [SonarSource/helm-chart-sonarqube#82]
Hi, I'm trying to undertand how to use this helm chart with an external database on Azure SQL. 
Firstly, I tried to install this helm chart using the following parameters:
`helm upgrade --install -f values.yaml --set postgresql.enabled=false --set jdbcUrlOverride="jdbc:sqlserver://DATABASE_NAME.database.windows.net:1433;database=demo;username=user;password=pass" -n sonarqube sonarqube-lts ./" `

The deployment looks to be installed, the sonarqube pod running but it show some issue with the HTTP server.

I am not pretty sure what is the way to use it with an external database (Azure SQL).

**Comment by JimFran** [comment]
The issue with the database is already resolved. For azure sql the url should be specified like this:

jdbcUrlOverride="jdbc:sqlserver://mydb.database.windows.net:1433;nameDatabase=test"

I have a couple if question at this point.

As you mention i can pass multiple -f parameters as inputs like secrets:

"helm install -f mysecrets.yaml -f values.yaml -n sonarqube sonarqube-lts ./ . . . "

So in case that I want to inject the username and password from a secret file i need to uncomment this part of the code from values.yaml:

  # To use an external PostgreSQL instance, set enabled to false and uncomment
  # the line below:
  # postgresqlServer: ""
  # To use an external secret for the password for an external PostgreSQL
  # instance, set enabled to false and provide the name of the secret on the
  # line below:
  **existingSecret: "mysecrets"**  
  # existingSecretPasswordKey: "postgresql-password"

i'm trying to  setup the usename and password through an existing secrets but seems that i'm not doing something correct:

"helm install -f mysecrets.yaml -f values.yaml -n sonarqube sonarqube-lts ./ . . . --set postgresqlUsername=username -- set postgresqlPassword=password . . ."


Also my last question is regarding persistence volumes. I enabled persistence but i cannot see that the charm creates any volumes for "extensions" just for "data". It is not necessary to create any volume for "extensions"?

**Comment by k3rnelpan1c-dev** [comment]
Hi Jim,

depending on if you are willing to a. wait a bit and b. willing to use the non lts version of this helm chart (don't worry you can still host the lts SonarQube version this way) I would recommend you wait for #28 to be merged.
It overhauls how you can define a external Database connection like you are trying to do and aims to make it a lot simpler.

In the meantime, if you are trying to use a external K8s secret you indeed would need the `existingSecret` and, if you have a custom key used in that secret (currently anything besides `postgresql-password`), you would need `existingSecretPasswordKey` too.
The one you would set to the name of the secret you have deployed within your 'sonarqube' namespace and the other to the key that the password is stored under within the secret.

Hope that helps and explains it well enough. :wink:

**Comment by JimFran** [comment]
Hi k3rnelpan1c-dev,

Not sure if i followed your point. So if i want to use "mysecrets.yml" (i have to deploy it previously in my sonarqube namespace) for the username/password i have to specify the secrets file in **existingSecret: "mysecrets"** and also the variable **existingSecretPasswordKey="variablepassword"** (where "variablepassword" is the keyword specified in mysecrets.yml file) in the values.yml file, isn't it?

Should i still using the "postgresqlUsername" and "postgresqlUsername" variables in the helm command?

_helm install -f values.yaml -n sonarqube sonarqube-lts ./ . . . --set postgresqlUsername=username -- set postgresqlPassword=variablepassword . . ._

in other case, may you give me an example of how you would use that external secret file?

**Comment by k3rnelpan1c-dev** [comment]
Hey Jim,

yes, if you are trying to use a `existingSecret` the secret has to be already deployed within the namespace you deploy the Helm Chart to.
IIRC Helm itself has also some CLI params to provide secrets while you install a chart but may be me remembering things, so please don't quote me on it.

Regarding the `postgresqlUsername` and `postgresqlPassword` properties, they will be ignored if you use a `existingSecret` so you wont need to provide those anymore.

A example for your deployment woud look something in the likes of this: (note this is psudo config/code)

> the secret you will want to have applied in your namespace (e.g. sonarqube in this example)
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: mySupeSecret
  namespace: sonarqube
type: Opaque
data:
  myDatabasePw: <base64-endoded-pw>
```

>how you want to install the chart (in this case taking all default values besides the ones overwritten in this cli example, you can always write your own values yaml to check into a Git and apply that via the Hlem cli instead of the manual overwrites)
```bash
helm install -n sonarqube helm-instal-name --set jdbcUrlOverride="jdbc://..." --set postgresql.existingSecret=mySupeSecret --set postgresql.existingSecretPasswordKey=myDatabasePw <sonarqubeChartDir>
```


Hope this clears things up ;)

**Comment by tobias-trabelsi-sonarsource** [comment]
now that the pending PR from @k3rnelpan1c-dev has been merged, can you adapt your configuration and try again?

**Comment by JimFran** [comment]
Hi Tobias, we will do it this week and let you know. Thanks.

**Comment by JimFran** [comment]
Hi @k3rnelpan1c-dev and @tobias-trabelsi-sonarsource,

the deployment finally worked! 

I deployed a secret.yml file and modified the URL to include the "postgresql.existingSecret" and "postgresql.existingSecretPasswordKey" as suggested and it is working fine.

Regarding the "Key Vaul" in Azure, do you think i can integrate this with the helm chart?

thanks and regards,

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @JimFran 

glad that it's now working for you. i think the general usage of a vault provider to manage kubernetes secrets is a little out of scope here. 
for sonarqube there should be no problem with letting secrets being managed by a secret provider. All necessary secrets for SQ (database, monitoring passcode)  are sourced during the startup. how well this plays together with other entities in your cluster is up to you i guess.

i will go ahead and close this ticket now as the original problem seems to be solved. best of luck in your future endeavors
